### ISSUE TITLE
class 101

### ISSUE THREAD

**Issue by esteimanuel** [huubvh/DiceGame#1]
https://github.com/huubvh/DiceGame/blob/99004d3571e807b528ad3314da0def8fde4e026d/Dice.cs#L7

A class can be thought of as being the blueprint of an object.

So the Dice class can be used to create a **new Dice**
``` c#
var dice = new Dice();
```

A dice has can have properties such as number of sides.
``` c#
public class Dice
{
    public int NumberOfSides { get; }

    public Dice(int numberOfSides)
    {
        this.NumberOfSides = numberOfSides;
    }
}
```

Now it's possible to create different types of dice.
``` c#
// create a dice with 6 sides
var d6 = new Dice(6); 
d6.NumberOfSides // will be 6

// create a dice with 20 sides
var d20 = new Dice(20); 
d20.NumberOfSides // will be 20
```

But what's the use if you can't even roll your fancy new dice. 
I think it's time to add some behavior.
``` c#
public class Dice
{
    private readonly Random random;

    public int NumberOfSides { get; }

    public Dice(int numberOfSides)
    {
        this.NumberOfSides = numberOfSides;
        this.random = new Random();
    }

    public int Roll()
    {
        var min = 1;
        var max = this.numberOfSides;
        var result = this.random.Next(min, max + 1);
        return result;
}
```

Let's roll the dice, because poppa needs some new shoes.
``` c#
// use our blueprint to create a new dice
var d6 = new Dice(6);

// now that we have a dice object it's possible to roll it using our newly added behavior
var result = d6.Roll();
```

**Comment by huubvh** [comment]
ok, I understand dice class wasn't used as a class as it contained more of a method than a class. Now I changed it accordingly so an object (including it's possible behaviour) is instantiated so I can use the instance in my code if I want it to behave, instead of the 'class' I formerly had.
